export const AIRPORTS = [
  "MCT - Muscat International Airport, Oman",
  "SLL - Salalah Airport, Oman",
  "KHS - Khasab Airport, Oman",
  "DQM - Duqm International Airport, Oman",
  "AUH - Zayed International Airport, Abu Dhabi, United Arab Emirates",
  "DXB - Dubai International Airport, United Arab Emirates",
  "SHJ - Sharjah International Airport, United Arab Emirates",
  "DWC - Al Maktoum International Airport, Dubai, United Arab Emirates",
  "DOH - Hamad International Airport, Doha, Qatar",
  "BAH - Bahrain International Airport, Bahrain",
  "KWI - Kuwait International Airport, Kuwait",
  "RUH - King Khalid International Airport, Riyadh, Saudi Arabia",
  "JED - King Abdulaziz International Airport, Jeddah, Saudi Arabia",
  "DMM - King Fahd International Airport, Dammam, Saudi Arabia",
  "MED - Prince Mohammad bin Abdulaziz International Airport, Madinah, Saudi Arabia",
  "CAI - Cairo International Airport, Egypt",
  "AMM - Queen Alia International Airport, Amman, Jordan",
  "BEY - Beirut-Rafic Hariri International Airport, Lebanon",
  "IST - Istanbul Airport, Turkiye",
  "SAW - Sabiha Gokcen International Airport, Istanbul, Turkiye",
  "LHR - Heathrow Airport, London, United Kingdom",
  "LGW - Gatwick Airport, London, United Kingdom",
  "MAN - Manchester Airport, United Kingdom",
  "CDG - Charles de Gaulle Airport, Paris, France",
  "ORY - Paris Orly Airport, France",
  "FRA - Frankfurt Airport, Germany",
  "MUC - Munich Airport, Germany",
  "AMS - Amsterdam Schiphol Airport, Netherlands",
  "BRU - Brussels Airport, Belgium",
  "ZRH - Zurich Airport, Switzerland",
  "GVA - Geneva Airport, Switzerland",
  "FCO - Leonardo da Vinci-Fiumicino Airport, Rome, Italy",
  "MXP - Milan Malpensa Airport, Italy",
  "MAD - Adolfo Suarez Madrid-Barajas Airport, Spain",
  "BCN - Barcelona-El Prat Airport, Spain",
  "VIE - Vienna International Airport, Austria",
  "CPH - Copenhagen Airport, Denmark",
  "ARN - Stockholm Arlanda Airport, Sweden",
  "OSL - Oslo Airport, Norway",
  "HEL - Helsinki Airport, Finland",
  "ATH - Athens International Airport, Greece",
  "WAW - Warsaw Chopin Airport, Poland",
  "PRG - Vaclav Havel Airport Prague, Czech Republic",
  "BUD - Budapest Ferenc Liszt International Airport, Hungary",
  "DME - Domodedovo International Airport, Moscow, Russia",
  "SVO - Sheremetyevo International Airport, Moscow, Russia",
  "JFK - John F. Kennedy International Airport, New York, United States",
  "EWR - Newark Liberty International Airport, New York, United States",
  "LAX - Los Angeles International Airport, United States",
  "ORD - O'Hare International Airport, Chicago, United States",
  "ATL - Hartsfield-Jackson Atlanta International Airport, United States",
  "DFW - Dallas Fort Worth International Airport, United States",
  "SFO - San Francisco International Airport, United States",
  "IAD - Dulles International Airport, Washington DC, United States",
  "YYZ - Toronto Pearson International Airport, Canada",
  "YVR - Vancouver International Airport, Canada",
  "DEL - Indira Gandhi International Airport, Delhi, India",
  "BOM - Chhatrapati Shivaji Maharaj International Airport, Mumbai, India",
  "HYD - Rajiv Gandhi International Airport, Hyderabad, India",
  "MAA - Chennai International Airport, India",
  "BLR - Kempegowda International Airport, Bengaluru, India",
  "COK - Cochin International Airport, Kochi, India",
  "CCJ - Calicut International Airport, Kozhikode, India",
  "TRV - Thiruvananthapuram International Airport, India",
  "CNN - Kannur International Airport, India",
  "GOI - Goa Dabolim Airport, India",
  "GOX - Manohar International Airport, Goa, India",
  "AMD - Sardar Vallabhbhai Patel International Airport, Ahmedabad, India",
  "ATQ - Sri Guru Ram Dass Jee International Airport, Amritsar, India",
  "LKO - Chaudhary Charan Singh International Airport, Lucknow, India",
  "JAI - Jaipur International Airport, India",
  "CCU - Netaji Subhas Chandra Bose International Airport, Kolkata, India",
  "CMB - Bandaranaike International Airport, Colombo, Sri Lanka",
  "MLE - Velana International Airport, Male, Maldives",
  "KTM - Tribhuvan International Airport, Kathmandu, Nepal",
  "DAC - Hazrat Shahjalal International Airport, Dhaka, Bangladesh",
  "CGP - Shah Amanat International Airport, Chattogram, Bangladesh",
  "KHI - Jinnah International Airport, Karachi, Pakistan",
  "LHE - Allama Iqbal International Airport, Lahore, Pakistan",
  "ISB - Islamabad International Airport, Pakistan",
  "PEW - Bacha Khan International Airport, Peshawar, Pakistan",
  "KBL - Kabul International Airport, Afghanistan",
  "IKA - Imam Khomeini International Airport, Tehran, Iran",
  "MHD - Mashhad International Airport, Iran",
  "KUL - Kuala Lumpur International Airport, Malaysia",
  "SIN - Singapore Changi Airport, Singapore",
  "BKK - Suvarnabhumi Airport, Bangkok, Thailand",
  "DMK - Don Mueang International Airport, Bangkok, Thailand",
  "HKT - Phuket International Airport, Thailand",
  "CGK - Soekarno-Hatta International Airport, Jakarta, Indonesia",
  "DPS - Ngurah Rai International Airport, Bali, Indonesia",
  "MNL - Ninoy Aquino International Airport, Manila, Philippines",
  "CEB - Mactan-Cebu International Airport, Philippines",
  "HAN - Noi Bai International Airport, Hanoi, Vietnam",
  "SGN - Tan Son Nhat International Airport, Ho Chi Minh City, Vietnam",
  "HKG - Hong Kong International Airport, Hong Kong",
  "CAN - Guangzhou Baiyun International Airport, China",
  "PVG - Shanghai Pudong International Airport, China",
  "PEK - Beijing Capital International Airport, China",
  "PKX - Beijing Daxing International Airport, China",
  "NRT - Narita International Airport, Tokyo, Japan",
  "HND - Haneda Airport, Tokyo, Japan",
  "ICN - Incheon International Airport, Seoul, South Korea",
  "SYD - Sydney Airport, Australia",
  "MEL - Melbourne Airport, Australia",
  "PER - Perth Airport, Australia",
  "AKL - Auckland Airport, New Zealand",
  "NBO - Jomo Kenyatta International Airport, Nairobi, Kenya",
  "ADD - Addis Ababa Bole International Airport, Ethiopia",
  "DAR - Julius Nyerere International Airport, Dar es Salaam, Tanzania",
  "JNB - O. R. Tambo International Airport, Johannesburg, South Africa",
  "CPT - Cape Town International Airport, South Africa",
  "LOS - Murtala Muhammed International Airport, Lagos, Nigeria",
  "CMN - Mohammed V International Airport, Casablanca, Morocco",
] as const;
